config/routes.rb
Rails.application.routes.draw do
  resources :wishlists_for_guests, path: "/i/", param: :token, only: [:show]
  devise_for :users, skip: [:sessions, :registrations]

  authenticated :user do
    root to: "wishlists#index"
  end

  devise_scope :user do
    root to: "devise/sessions#new"

    get "sign_in" => "devise/sessions#new", as: :new_user_session
    post "sign_in" => "devise/sessions#create", as: :user_session

    get "sign_up" => "devise/registrations#new", as: :new_user_registration
    post "sign_up" => "devise/registrations#create", as: :user_registration

    delete "sign_out" => "devise/sessions#destroy", as: :destroy_user_session
  end

  resources :wishlists do
    resources :items, only: %i(new create edit update destroy) do
      resources :reservations, only: %i(create destroy)
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can %i(create read destroy update), Wishlist, user_id: user.id
      can %i(create update destroy), Item, wishlist: { user_id: user.id }
      can %i(destroy), Reservation, item: { wishlist: { user_id: user.id } }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/tokenable.rb
module Tokenable
  extend ActiveSupport::Concern

  included do
    after_initialize :set_token
  end

  protected

  def set_token
    return if self.token
    self.token = loop do
      random_token = SecureRandom.uuid
      break random_token unless self.class.exists?(token: random_token)
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :wishlist
  has_one :reservation, dependent: :destroy

  validates :name, presence: true

  def reserved?
    reservation.present?
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  has_many :wishlists, dependent: :destroy
  devise :database_authenticatable, :registerable, :validatable

  MINIMUM_PASSWORD_LENGTH = 6
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  include Tokenable

  belongs_to :user
  has_many :items, dependent: :destroy

  validates :name, presence: true
  validates :token, presence: true, uniqueness: true

  scope :created_by, ->(user) { where(user_id: user.id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  private

  def after_sign_in_path_for(_)
    root_path
  end

  def after_sign_up_path_for(_)
    root_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wishlist, only: %i(new create edit update destroy)
  before_action :set_item, only: %i(edit update destroy)

  def new
    @item = @wishlist.items.new
    authorize! :new, @item
  end

  def create
    @item = @wishlist.items.new(item_params)
    authorize! :create, @item
    @item.save!
    redirect_to @wishlist, notice: t(".success")
  rescue ActiveRecord::RecordInvalid
    flash[:error] = t(".failure")
    render :new
  end

  def edit
    authorize! :edit, @item
  end

  def update
    authorize! :update, @item
    @item.update_attributes!(item_params)
    redirect_to @wishlist, notice: t(".success")
  rescue ActiveRecord::RecordInvalid
    flash[:error] = t(".failure")
    render :edit
  end

  def destroy
    authorize! :destroy, @item
    @item.destroy!
    redirect_to @wishlist, notice: t(".success")
  rescue ActiveRecord::RecordNotDestroyed
    redirect_to wishlist, error: t("generic_error")
  end

  private

  def item_params
    params.require(:item).permit(:name, :description)
  end

  def set_wishlist
    @wishlist = Wishlist.find(params[:wishlist_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to wishlists_url, alert: t("generic_error")
  end

  def set_item
    @item = @wishlist.items.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to @wishlist, alert: t("generic_error")
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!, except: :create

  def create
    @reservation = Reservation.new(item_id: params[:item_id])
    return unless @reservation.save
    redirect_to wishlists_for_guest_path(Wishlist.find(params[:wishlist_id]).token), notice: t(".success")
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    authorize! :destroy, @reservation
    @reservation.destroy!
    redirect_to wishlist_path(params[:wishlist_id]), notice: t(".success")
  rescue CanCan::AccessDenied, ActiveRecord::RecordNotDestroyed
    redirect_to wishlist_path(params[:wishlist_id]), alert: t("generic_error")
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wishlist!, only: %i(destroy edit update)

  def index
    authorize! :index, Wishlist
    @wishlists = Wishlist.created_by(current_user)
  end

  def new
    @wishlist = Wishlist.new(wishlist_params)
    authorize! :new, @wishlist
  rescue CanCan::AccessDenied
    redirect_to wishlists_path, alert: t("generic_error")
  end

  def create
    @wishlist = Wishlist.new(wishlist_params)
    authorize! :create, @wishlist
    @wishlist.save!
    redirect_to wishlists_path, notice: t(".success")
  rescue CanCan::AccessDenied
    redirect_to wishlists_path, alert: t("generic_error")
  rescue ActiveRecord::RecordInvalid
    flash[:error] = t(".failure")
    render :new
  end

  def show
    @wishlist = Wishlist.find(params[:id])
    authorize! :show, @wishlist
  rescue ActiveRecord::RecordNotFound, CanCan::AccessDenied
    redirect_to wishlists_path, alert: t("generic_error")
  end

  def destroy
    authorize! :destroy, @wishlist
    @wishlist.destroy!
    redirect_to wishlists_path, notice: t(".success")
  rescue CanCan::AccessDenied, ActiveRecord::RecordNotDestroyed
    redirect_to wishlists_path, alert: t("generic_error")
  end

  def edit
    authorize! :edit, @wishlist
  rescue CanCan::AccessDenied
    redirect_to wishlists_path, alert: t("generic_error")
  end

  def update
    authorize! :update, @wishlist
    @wishlist.update_attributes!(wishlist_params)
    redirect_to @wishlist, notice: t(".success")
  rescue CanCan::AccessDenied
    redirect_to wishlists_path, alert: t("generic_error")
  rescue ActiveRecord::RecordInvalid
    render :edit
  end

  private

  def wishlist_params
    params[:wishlist] ||= {}
    params[:wishlist][:user_id] = current_user.id
    params.require(:wishlist).permit(:user_id, :name, :description)
  end

  def set_wishlist!
    @wishlist = Wishlist.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to wishlists_path, alert: t("generic_error")
  end
end

app/controllers/wishlists_for_guests_controller.rb
class WishlistsForGuestsController < ApplicationController
  def show
    @wishlist = Wishlist.find_by(token: params[:token])
    render file: "public/404" unless @wishlist
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/items/_item_form.html.erb
<%= form_for([@wishlist, @item]) do |f| %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", rows: "9" %>
  </div>

  <%= f.submit button_name, class: "btn btn-default btn-success pull-right" %>
<% end %>

app/views/items/edit.html.erb
<div class="row">
  <div class="container col-md-6 col-md-offset-3">
    <h1 class="form-header">Edit a gift!</h1>

    <%= render partial: "item_form", locals: { button_name: "Update" } %>
  </div>
</div>

app/views/items/new.html.erb
<div class="row">
  <div class="container col-md-6 col-md-offset-3">
    <h1 class="form-header">Create a gift!</h1>

    <%= render partial: "item_form", locals: { button_name: "Create" } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>Wizlist — Your wishlists. Not your problem.</title>
    <meta name="description" content="">
    <%= csrf_meta_tags -%>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all' -%>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= render "shared/navigation" -%>
    <% end %>

    <%= yield -%>

    <%= javascript_include_tag 'application' %>
    <%= render "shared/flash_messages", flash: flash %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<script>
  $.notifyDefaults({
    placement: {
      from: "top",
      align: "center"
    },
    offset: {
      x: 0,
      y: 55
    }
  })
</script>
<script>
  $(document).ready(function() {
    <% flash.each do |type, message| %>
      $.notify({
        message: "<%= message -%>"
      }, {
        type: "<%= type.to_s -%>"
      });
    <% end %>
  });
</script>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <ul class="nav navbar-nav">
      <li><%= link_to "Wizlist", root_path, class: "navbar-brand header-logo" -%></li>

      <li><%= link_to t("index"), wishlists_path -%></li>

      <li class="navbar-sign-out">
        <span class="navbar-text">
          <%= t("signed_in_as") -%> <span class="navbar-email"><%= current_user.email -%></span>
        </span>
        <%= button_to t("sign_out"), destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" -%>
      </li>
    </ul>
  </div>
</nav>

app/views/wishlists/_item.html.erb
<div class="wishlist-box breakable-words">
  <div class="thumbnail">
    <div class="caption">
      <h3><%= item.name %></h3>

      <p><%= item.description %></p>

      <%= link_to edit_wishlist_item_path(@wishlist, item), class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-edit"></span> Edit
      <% end %>

      <a class="btn btn-sm btn-danger-outline btn-primary" data-toggle="popover-with-html"
         data-placement="bottom" data-trigger="focus" tabindex="0"
         data-content-source=".item-<%= item.id -%>-delete-confirm">
        <span class="glyphicon glyphicon-remove"></span> Delete
      </a>
      <div class="item-<%= item.id -%>-delete-confirm hide">
        <%= t("delete_ask") -%>
        <%= link_to t("delete_confirm"),
            wishlist_item_path(wishlist_id: @wishlist.id, id: item.id),
            method: :delete, class: "btn btn-sm btn-danger" -%>
      </div>

      <div class="unreserve-button-display">
        <%= button_to([@wishlist, item, item.reservation], type: "submit", class: "btn btn-default btn-sm", method: :delete, disabled: !item.reserved?) do %>
          <span class="glyphicon glyphicon-minus-sign"></span>
          <%= item.reserved? ? t("reserved") : t("unreserved") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/wishlists/_wishlist_form.html.erb
<%= form_for(@wishlist) do |f| %>
  <% if @wishlist.errors.any? %>
    <ul>
      <% @wishlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", rows: "4" %>
  </div>

  <%= f.submit button_name, class: "btn btn-default btn-success pull-right"%>
<% end %>

app/views/wishlists/edit.html.erb
<div class="row">
  <div class="container col-md-6 col-md-offset-3">
    <h1 class="form-header">Edit your wishlist!</h1>

    <%= render partial: "wishlist_form", locals: { button_name: "Update" } %>
  </div>
</div>

app/views/wishlists/index.html.erb
<% content_for :title, t(".your_wishlists") %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
      <ul class="wlists">
        <li class="wlist wlist-new">
          <span class="wlist-name"><%= t(".wishlists_count", count: @wishlists.count) -%></span>
          <div class="wlist-actions">
            <%= link_to t(".create_new_wishlist"), new_wishlist_path,
                class: "btn btn-sm  btn-success-outline" -%>
          </div>
        </li>

        <% @wishlists.each do |wishlist| %>
          <li class="wlist">
            <%= link_to wishlist.name, wishlist, class: "wlist-name" -%>

            <div class="wlist-actions">
              <a class="btn btn-sm btn-primary" data-toggle="popover-with-html" data-placement="left"
                 data-trigger="focus" tabindex="0"
                 data-content-source="#wlist-<%= wishlist.id -%>-copy-link">
                <%= t("copy_link") -%>
              </a>
              <div id="wlist-<%= wishlist.id -%>-copy-link" class="hide">
                <div class="input-group input-group-sm">
                  <input id="wlist-<%= wishlist.id -%>-token" class="form-control"
                         readonly type="text"
                         value="<%= wishlists_for_guest_url(wishlist.token) %>">
                  <span class="input-group-btn">
                    <button class="btn btn-default js-clip" type="button"
                            data-clipboard-target="#wlist-<%= wishlist.id -%>-token">
                      <span class="glyphicon glyphicon-copy"></span>
                    </button>
                  </span>
                </div>
              </div>

              <%= link_to t("edit"), edit_wishlist_path(wishlist), class: "btn btn-sm btn-default" -%>

              <a class="btn btn-sm btn-danger-outline btn-primary"
                 data-toggle="popover-with-html" data-placement="left"
                 data-trigger="focus" tabindex="0"
                 data-content-source=".wlist-<%= wishlist.id -%>-delete-confirm">
                <%= t("delete") -%>
              </a>
              <div class="wlist-<%= wishlist.id -%>-delete-confirm hide">
                <span><%= t("delete_ask") -%></span>
                <%= link_to t("delete_confirm"), wishlist, method: :delete,
                    class: "btn btn-sm btn-danger" -%>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/wishlists/new.html.erb
<div class="row">
  <div class="container col-md-6 col-md-offset-3">
    <h1 class="form-header">Create your new wishlist!</h1>

    <%= render partial: "wishlist_form", locals: { button_name: "Create" } %>
  </div>
</div>

app/views/wishlists/show.html.erb
<div class="container">
  <h1 class="wishlist-name"><%= @wishlist.name %></h1>

  <p class="wishlist-description"><%= @wishlist.description %></p>

  <div class="input-group wishlist-url-display">
    <span class="input-group-addon">Link for sharing:</span>
    <input type="text" class="form-control" id="unique-url"
           value="<%= wishlists_for_guest_url(@wishlist.token) %>" readonly>
    <span class="input-group-addon btn js-clip" data-clipboard-target="#unique-url">copy</span>
  </div>

  <div class="wishlist-main-buttons">
    <%= link_to new_wishlist_item_path(@wishlist),
        class: "btn btn-success-outline" do %>
      <span class="glyphicon glyphicon-plus"></span> Add a gift
    <% end %>

    <%= link_to edit_wishlist_path(@wishlist), class: "btn btn-default" do %>
      <span class="glyphicon glyphicon-edit"></span> Edit list description
    <% end %>

    <a class="btn btn-danger-outline btn-primary" data-toggle="popover-with-html"
       data-placement="top" data-trigger="focus" tabindex="0"
       data-content-source=".wlist-<%= @wishlist.id -%>-delete-confirm">
      <span class="glyphicon glyphicon-remove"></span> Delete this list
    </a>
    <div class="wlist-<%= @wishlist.id -%>-delete-confirm hide">
      <span><%= t("delete_ask") -%></span>
      <%= link_to t("delete_confirm"), @wishlist, method: :delete,
          class: "btn btn-sm btn-danger" -%>
    </div>
  </div>

  <div class="container wishlists-row">
    <%= render partial: "item", collection: @wishlist.items %>
  </div>
</div>

app/views/wishlists_for_guests/_item.html.erb
<div class="wishlist-box breakable-words">
  <div class="thumbnail">
    <div class="caption">
      <h3><%= item.name %></h3>

      <p><%= item.description %></p>

      <%= form_for([@wishlist, item, Reservation.new]) do |f| %>
        <%= button_tag(type: 'submit', class: "btn btn-default btn-sm submit", disabled: item.reserved?) do %>
          <span class="glyphicon glyphicon-gift"></span>

          <%= item.reserved? ? t("gift_reserved") : t("gift_to_reserve") -%>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/wishlists_for_guests/show.html.erb
<div class="container">
  <h1 class="wishlist-name"><%= @wishlist.name %></h1>

  <p class="wishlist-description"><%= @wishlist.description %></p>

  <div class="container wishlists-row">
    <%= render partial: "item", collection: @wishlist.items %>
  </div>
</div>